### ISSUE TITLE
How to integrate into Tableau

### ISSUE THREAD

**Issue by jeremyfranklin** [weissleb/peloton-tableau-connector#1]
Hi there,

I use Tableau, but have never built a connector.  How could I use these files to run the connector?

**Comment by mistrb01** [comment]
I have the same question.  How would one use this connector.

**Comment by weissleb** [comment]
Hi @jeremyfranklin and @mistrb01 .  This is currently under development.  I have completed the backend (in a private repo for now), which does the hard work of finding your data and returning it in a JSON.  This is my first Tableau connector though, and while I have it working locally, there's still some work to do in order to make this public.

I'll be happy to update you either when it is complete and available on Tableau Public, or when I have it to a place where you could run it locally using Tableau Desktop.  Hopefully soon!

- weissler

**Comment by jeremyfranklin** [comment]
Thanks! I look forward to it!!!

Jeremy D. Franklin

**Comment by mistrb01** [comment]
I look forward to it as well!!

**Comment by mistrb01** [comment]
Also, if you need a beta tester I am sure that both of us are willing.

**Comment by weissleb** [comment]
For sure guys.  Couple of questions first.

1. Are you guys cycling, or doing something else?
2. Do you know how many cycling workouts you have?  One aspect that's tough to test with only my own accounts is the scale of retrieving thousands of rides, for example.

Appreciated!

**Comment by jeremyfranklin** [comment]
I’m mainly doing cycling, but also strength and bike boot camps. I mainly care about metrics for the biking. I only have just above 100 rides. My partner also has about 100 rides. 

Jeremy D. Franklin

**Comment by weissleb** [comment]
Here's the current schema.
```
{
    "tables": [
        {
            "name": "workouts",
            "description": "",
            "columns": [
                {
                    "name": "ExtractTimeUTC",
                    "goType": "time.Time"
                },
                {
                    "name": "Id",
                    "goType": "string"
                },
                {
                    "name": "StartTimeSeconds",
                    "goType": "uint64"
                },
                {
                    "name": "TimeZone",
                    "goType": "string"
                },
                {
                    "name": "StartTimeUTC",
                    "goType": "time.Time"
                },
                {
                    "name": "StartTime",
                    "goType": "time.Time"
                },
                {
                    "name": "Output",
                    "goType": "float32"
                },
                {
                    "name": "WasPR",
                    "goType": "bool"
                },
                {
                    "name": "CurrentPR",
                    "goType": "bool"
                },
                {
                    "name": "Type",
                    "goType": "string"
                },
                {
                    "name": "Status",
                    "goType": "string"
                },
                {
                    "name": "RideId",
                    "goType": "string"
                },
                {
                    "name": "RideTitle",
                    "goType": "string"
                },
                {
                    "name": "RideDifficulty",
                    "goType": "float32"
                },
                {
                    "name": "RideLevel",
                    "goType": "string"
                },
                {
                    "name": "Instructor",
                    "goType": "string"
                },
                {
                    "name": "InstructorImageURL",
                    "goType": "string"
                },
                {
                    "name": "DurationSeconds",
                    "goType": "uint16"
                },
                {
                    "name": "HasWeights",
                    "goType": "bool"
                }
            ]
        }
    ]
}
```

It allows me to analyze my PR's, which is my primary goal.  When do I PR, with which instructors, etc?  So, I could build a dashboard like this.

![image](https://user-images.githubusercontent.com/7568883/103387096-f55b0200-4acf-11eb-9ce6-0f376e428524.png)

I hope to make progress over the next few days.  Thanks again for your interest!

**Comment by mistrb01** [comment]
I have less than 20 rides so far.  I am just a data geek.

**Comment by weissleb** [comment]
@mistrb01 and @jeremyfranklin please take a look at the new README on the main branch, and let me know if you think you'd like to take this for a local spin.  If not, it's cool.  I really hope to get this available publicly rather quickly at this point (next week or two).

Thanks!

**Comment by jeremyfranklin** [comment]
@weissleb i will try it tomorrow.

**Comment by weissleb** [comment]
> @weissleb i will try it tomorrow.

Cool, I have added you as a collaborator on the REST server repo, which is still private.  Let me know if you run into trouble.

**Comment by mistrb01** [comment]
Can you add me as well?

**Comment by weissleb** [comment]
@mistrb01 , done.

I think I'm going to combine the REST server and this connector into one, which will simplify the whole thing before I deploy publicly.  I'll be creating a branch to do so.  For now, you can use the two repo's and follow the instructions in the README's.

Thanks guys!

**Comment by mistrb01** [comment]
I may be missing something because I am new to github.  I don't see the
branch for the rest server.

**Comment by mistrb01** [comment]
Never mind.  I am looking at peloton-data-extractor now.

**Comment by mistrb01** [comment]
I was able to get everything working.  Thank you.

**Comment by weissleb** [comment]
That's great @mistrb01 , now you'll have to let me know if it's actually useful 😄 .

**Comment by mistrb01** [comment]
It is useful.  Where can I find out which data points are available?  I may
ask to have more included.

**Comment by weissleb** [comment]
@mistrb01 good to hear.  Unfortunately, Peloton does not have a documented API.  I should be able to pull most of what you can see in the app itself.  If you find something there, or have specific questions you want to ask of the data, post here and I'll see what I can find.

**Comment by mistrb01** [comment]
Ok thanks very much.  I will look to see if there is something that I want
that you may be able to get that is not included with the workouts download
from the onepeloton website.

**Comment by jeremyfranklin** [comment]
Not sure I am doing it correctly.  I see this in the Terminal
<img width="568" alt="Screen Shot 2021-01-13 at 10 39 20 AM" src="https://user-images.githubusercontent.com/29869055/104488599-d78ba380-558b-11eb-9be4-c1e6bfee6abd.png"> and in Tableau I get the login info, but then I just see this after eating my credentials
<img width="853" alt="Screen Shot 2021-01-13 at 10 41 40 AM" src="https://user-images.githubusercontent.com/29869055/104488670-eeca9100-558b-11eb-90d7-67c6d6611d81.png">

**Comment by weissleb** [comment]
Sorry it's not clear @jeremyfranklin.  It looks like you didn't build the rest server from https://github.com/weissleb/peloton-data-extractor first.  It's not a public repo, but I made you a collaborator.

Once you follow the README there, you should then be able to just start the rest server, and then the connector.

I also just did a refactor on another branch, where I moved the rest server into the same app, so you wouldn't need that step.  If you want to wait a day or two, I will have that fully tested and the README updated.  In that case, you will be able to just build the connector and start it without the separate rest server.  Sorry for any confusion.

**Comment by weissleb** [comment]
@mistrb01 and @jeremyfranklin I've merged the rest server into the connector.  You no longer need to mess with the other repo, or start the rest server, as long as you ...

- Change into the directory where you cloned this repo.
- Get new changes with `git pull`.  
_If you get an error because you made changes, you can hang onto those changes with `git checkout -b my-branch && git checkout main`_
- Rebuild the executable with `go build -o wdc github.com/weissleb/peloton-tableau-connector`.
- At this point, you're good, and going forward you just need to start the connector with `$HOME/peloton-tableau-connector/wdc`

I hope this is more convenient.  Nothing should change on the Tableau side.  

I appreciate you guys being my alpha testers!

**Comment by jeremyfranklin** [comment]
Thanks! Just tried it and it worked very easily.

**Comment by jeremyfranklin** [comment]
It would be great to get all the information that is in the export you can do from your profile page (e.g. average heart rate, average cadence, average resistance, calories burned, etc)

**Comment by mistrb01** [comment]
I am going to try the single repository instructions today.

In addition, I would like to add average heart rate, max heart rate to his
list.

**Comment by weissleb** [comment]
Ok, I see how they're pulling the download.  @mistrb01, average heart rate is there, but _not_ max heart rate.

I've spent today getting the current version online (see updates to [README](https://github.com/weissleb/peloton-tableau-connector/blob/main/README.md)).  The URL is currently `https://warm-shore-62344.herokuapp.com`.

I'll see how quickly I can add these other metrics.

One thing I could use feedback on, is how important it is for you to know whether or not a workout had weights.  It was important to me at first, since I was analyzing PR's, and obviously I am not going to PR when there are weights, so I wanted to be able to filter those workouts out.  I'm no longer sure that this is all that important, and it's an extra API call, *per workout* to get it.

I really appreciate your feedback so far!

**Comment by mistrb01** [comment]
First of all, thank you for your time and efforts to get this going.  I do
not use weights as of yet, so I don’t need it.  I am not sure if I would
use that field even if I were using them.

Thanks again,
George

**Comment by jeremyfranklin** [comment]
This is amazing work. I don't really use the have weights column or need to filter it out. I don't really take many bike workouts with weights

**Comment by weissleb** [comment]
Ok @mistrb01 and @jeremyfranklin, I've changed the schema to include the metrics in the Peloton export.  Some stuff will break, but is easily fixed -- let me know if you need help.

You can pull down the code and run it locally again, or use the online version.  I put up a little [home page](https://warm-shore-62344.herokuapp.com/home) -- no laughing at my HTML, front-end work aint my bag.

As always, your feedback is appreciated, and welcomed!

**Comment by mistrb01** [comment]
The online version worked fine.  I was already connected from yesterday and
did a refresh.

The local version didn't work.  I got the error that $PORT must be set.  I
copied the config.go file from the old version to the new version and it
didn't fix the issue.
 George

**Comment by mistrb01** [comment]
And yes, I ran the go build command.

**Comment by weissleb** [comment]
Yeah sorry @mistrb01, minor change to the instructions in the README.  Now you have to set the PORT environment variable.  Change your executable command to `export PORT=8889 && $HOME/peloton-tableau-connector/wdc`, and you should be good.

**Comment by mistrb01** [comment]
Ok, this time I followed instructions from the readme file and everything
worked fine.

**Comment by weissleb** [comment]
Hi @mistrb01 and @jeremyfranklin , I I'm gonna close this issue, as it seems you're both able to use the connector, locally and online at `https://warm-shore-62344.herokuapp.com`.  

Please feel free to open new issues if you run into trouble, or would like to request additional metrics and/or dimensions.

Thank you so much for your willingness to give this a shot.  Ride on!
