### ISSUE TITLE
Average Output Not Correct

### ISSUE THREAD

**Issue by ellisjw** [weissleb/peloton-tableau-connector#9]
![Screen Shot 2021-02-02 at 4 43 54 PM](https://user-images.githubusercontent.com/32772787/106677509-1226a180-6576-11eb-8b0b-f73560e66133.png)
Nice Dashboards! 

In the screenshot above, you list the Average Output, but that appears to be the total output for the ride.

**Comment by ellisjw** [comment]
If I am correct, then the label on the Y Axis is also "Total Output", not "Average Output"

**Comment by weissleb** [comment]
@ellisjw nice catch.  Luckily, since each data point on the chart is in fact a single ride, the values of the data were accurate (no aggregation was occurring).  That stated, the label was certainly wrong, and is now fixed.  Thanks!
